# -*- coding: utf-8 -*-
"""111208094_ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSDgJcjnX8wkrMSxV3ghZ21MdcXyWaDY

#Question

##2.
Python to design a program with 4 students and 25 apples, distributing
the apples evenly among the students. Each student should receive the
maximum number of apples, and the apple count per student must be
equal. Print “the number of apples each student receives and the number
of remaining apples“.
"""

x1=25//4 #each student should receive the maximum number of apples

x2=25%4 #the number of remaining apples

print("the number of apples each student receives :",x1)
print("the number of remaining apples:",x2)

"""##3.
A company has determined that its annual profit is typically 23 percent
of total sales. Write a program that the projected amount of total sales is
5000, and then display the profit that will be made from that amount.
"""

profit=5000*0.23  # total sales*percent
print(profit)

total_sales=int(input("enter total sales:"))

per=float(input("enter percent:"))

profit=total_sales*per
print(profit)