# -*- coding: utf-8 -*-
"""111208094_ex3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jO7KHvSBgaquw1XOhuj2-CBB6XsvczsU

# Question 1: calculates BMI
Write a Python program that requires user to input height(cm)and weight(kg) and determine the BMI based on the following formula :

BMI=weight(kg)/height2(m2).

* If less than 18.5 (excluding 18.5), print underweight
* If between 18.5~24 (excluding 24), print normal
* If between 24 ~ 27 (excluding 27), print overweight
* If greater than 27, print obese
"""

weight=float(input("請輸入體重(kg):"))
height=float(input("請輸入身高(cm):"))
height=height/100
BMI=weight/(height**2)
if BMI<18.5:
    print(f"您的BMI為{BMI},體重過輕")
elif BMI<24:
    print(f"您的BMI為{BMI},體重正常")
elif BMI<27:
    print(f"您的BMI為{BMI},體重過重")
else:
    print(f"您的BMI為{BMI},體重肥胖")

"""# Question 2
Write an program that displays 'Speed is normal' if the speed
variable is within the range of 24 to 56. If the speed variable’s value
is outside this range, display 'Speed is abnormal'.
"""

speed=float(input("請輸入速度:"))
if 24<=speed<=56:
    print("Speed is normal")
else:
    print("Speed is abnormal")

"""# Question 3
Serendipity Booksellers has a book club that awards points to its
customers based on the number of books purchased each month. The
points are awarded as follows:

* If a customer purchases 0 books, he or she earns 0 points.
* If a customer purchases 1 book, he or she earns 5 points.
* If a customer purchases 2 books, he or she earns 15 points.
* If a customer purchases 3 books, he or she earns 30 points.
* If a customer purchases 4 or more books, he or she earns 60 points.

Write a program that asks the user to enter the number of books
"""

books=int(input("enter the number of books:"))
if books == 0:
    print("You will earn 0 points.")
elif books == 1:
    print("You will earn 5 points.")
elif books == 2:
    print("You will earn 15 points.")
elif books == 3:
    print("You will earn 30 points.")
elif books >=4 :
    print("You will earn 60 points.")
else:
    print("輸入錯誤")