# -*- coding: utf-8 -*-
"""111208094_ex6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTPsrbU0GcuFuBPk_Ke_gU8Vks4W3NPR

## Q1
"""

listA=[1,2,3,4,5,6,7,8,9,10,11]

#print [1,3,5,7,9] from listA
print(listA[0:10:2])

#The last three values [9,10,11] from listA
print(listA[-3:])

"""## Q2

Find the negative numbers and print them from x= [1,3,-7,4, 9, -5,4]

• Print the result

• 第3個數值是負數:-7

• 第6個數值是負數:-5
"""

x= [1,3,-7,4, 9, -5,4]

for i, num in enumerate(x): #enumerate(x): 同時取得每個元素的索引（位置）和值
    if num < 0:
        print(f"第{i+1}個數值是負數:{num}")

"""## Q3

Let users input some messages and save these messages in a list until users enter n/N

Prompt: “Enter some messages:”

Then, prompt: “do you want to continue entering?(Y/y or N/n)”

Finally, print this list
"""

messages = []

while True:
    message = input("Enter some messages: ")
    messages.append(message)

    continue_or_not = input("Do you want to continue entering? (Y/y or N/n): ")
    if continue_or_not.lower() == 'n':
        break
    else:
      continue

print("All the messsage you enter：")
print(messages)