# -*- coding: utf-8 -*-
"""111208094_ex5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZqIylVBX_lh4c1IQO0pZHLqPIyIiRMXL

## Basic Question 5:
Complete the “number guessing program” Write a program to make computer pick a random positive
integer (0-100), then let user guess the number. (“Please input a
positive integer (0-100):”)。

The program determine the value user input, if it greater than the
truth value, print ”The number you guessed is too big” ; if it less
than the truth value, print ”The number you guessed is too small”
; if they are the exact same number, print ”congrat, you’re right.”
Let the user keep guessing until the right answer appears.
"""

import random

y = random.randint(1, 100)

while True:
    x = int(input("Please input a positive integer (0-100): "))

    if x == y:
        print("Congrat, you’re right.")
        break
    elif x > y:
        print("The number you guessed is too big.")
    elif x < y:
        print("The number you guessed is too small.")

"""跟上次的有點不一樣，我有稍微修一下

後來我才發現
x = int(input("Please input a positive integer (0-100): "))
其實不用那麼多次XD

## Advance Question 4_A-1
Write a program which repeatedly reads numbers until the user
enters “done”. Once “done” is entered, print out the total, count,
and average of the numbers.
"""

num=[]

while True:
  x=input("Please input a number:")
  if x=="done":
     num = list(map(int, num))
     print("Total",sum(num))
     print("Count",len(num))
     print("Average",sum(num)/len(num))
     break
  else:
    num.append(x)