# -*- coding: utf-8 -*-
"""111208094_ex4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Av6Za8tEcfnmMuUL4_Tp6VPxqMQCI2Q3

#Basic

## Q1
"""

while True:
    x = float(input("請輸入三角形的第一個邊: "))
    y = float(input("請輸入三角形的第二個邊: "))
    z = float(input("請輸入三角形的第三個邊: "))

    if x + y > z and y + z > x and x + z > y:
        print("這是一個三角形！")
        break
    else:
        print("這不是一個三角形，請再輸入一次！")

"""## Q2"""

for i in range(5):
    print(f"{' ' * i}#")
for i in range(3, -1, -1):  #第六個#是往右三格
    print(f"{' ' * i}#")

"""## Q3"""

x=0
for i in range(-1,-100,-2):
  x+=i
print(x)

"""## Q4"""

x=0
y=0
z=0
u=[]
for i in range(1,31):
  x=i
  y=31-i
  z=x/y
  u.append(z)
v=sum(u)
print(v)

#GPT給的簡短答案
v = sum(i / (31 - i) for i in range(1, 31))
print(v)

"""## Q5"""

import random

x=int(input("Please input a positive integer (0-100):"))
y=random.randint(1, 100)

while True:
 if x==y:
   print("Congrat, you’re right.")
   break
 elif x>y:
   print("The number you guessed is too big.")
   x=int(input("Please input a positive integer (0-100):"))
 elif x<y:
   print("The number you guessed is too small.")
   x=int(input("Please input a positive integer (0-100):"))
 else:
   print("Please input a positive integer (0-100).")

"""# Advanced

## Q1
"""

num=[]

while True:
  x=input("Please input a number:")
  if x=="done":
     num = list(map(int, num))
     print("Total",sum(num))
     print("Count",len(num))
     print("Average",sum(num)/len(num))
     break
  else:
    num.append(x)

"""## Q2

"""



"""## Q3"""

