# -*- coding: utf-8 -*-
"""111208094_ex2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jO7KHvSBgaquw1XOhuj2-CBB6XsvczsU

# Q1
"""

import math

x1=float(input("enter x1:"))
x2=float(input("enter x2:"))
y1=float(input("enter y1:"))
y2=float(input("enter y2:"))

distance=float(math.sqrt((x2-x1)**2+(y2-y1)**2))
print(f"the distance of the points is {distance}")

"""# Q2"""

import math

first_name = str(input("enter your first name: "))
last_name = str(input("enter your last name: "))
student_id = str(input("enter your student id: "))

print("If your name is ", first_name ,last_name,"and your ID is", student_id,".")
print(f"Your login name is {first_name[0:3]}{last_name[0:3]}{student_id[-3:]}")
#For example, if a student’s name is Amanda Spencer, and her ID number is ENG6721, her login name would be AmaSpe721.