# -*- coding: utf-8 -*-
"""Group16_Discussion_ex7 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZJYvnwb0zPgDLwJDTGsD8pstYFcWdeC

## Question 1: Word Frequency (cont.)

Then, find words with the maximum and
minimum times

Print:

A. The dictionary

B. Appear words of the max. and min. times
"""

# question_1
songstr="""
You're insecure
Don't know what for
You're turning heads
When you walk through the do-o-or
Don't need make up
To cover up
Being the way that you are is en-o-ough
Everyone else in the room can see it
Everyone else but you
Baby you light up my world like nobody else
The way that you flip your hair gets me overwhelmed
But when you smile at the ground it ain't hard to tell
You don't know oh oh
You don't know you're beautiful
If only you saw what I can see
You'll understand why I want you so desperately
Right now I'm looking at you and I can't believe
You don't know oh oh
You don't know you're beautiful
Oh oh
That's what makes you beautiful
So c-come on
You got it wrong
To prove I'm right I put it in a so-o-ong
I don't know why
You're being shy
And turn away when I look into your ey-e-es
Everyone else in the room can see it
Everyone else but you
Baby you light up my world like nobody else
The way that you flip your hair gets me overwhelmed
But when you smile at the ground it ain't hard to tell
You don't know oh oh
You don't know you're beautiful
If only you saw what I can see
You'll understand why I want you so desperately
Right now I'm looking at you and I can't believe
You don't know oh oh
You don't know you're beautiful
Oh oh
That's what makes you beautiful
Baby you light up my world like nobody else
The way that you flip your hair gets me overwhelmed
But when you smile at the ground it ain't hard to tell
You don't know oh oh
You don't know you're beautiful
Baby you light up my world like nobody else
The way that you flip your hair gets me overwhelmed
But when you smile at the ground it ain't hard to tell
You don't know oh oh
You don't know you're beautiful
If only you saw what I can see
You'll understand why I want you so desperately
Right now I'm looking at you and I can't believe
You don't know oh oh
You don't know you're beautiful
Oh oh oh
You don't know you're beautiful
Oh oh oh
That's what makes you beautiful
"""
songlist=songstr.split()
print(songlist)

songlist = songstr.lower().replace("-", "").replace(",", "").replace(".", "").replace("\n", " ").split()  #後面replace是清理資料用的(應該也可以不清理啦)
print(songlist)

# Step 2: 迴圈統計詞頻
word_count = {}  #dict裝：單字/出現次數
for word in songlist:
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

word_count

# Step 3: Max.Min
max_freq = max(word_count.values())
min_freq = min(word_count.values())

most_common = [] #這個是list，{}才是dict
least_common = []

for word in word_count:
    count = word_count[word]   #word_count[word]把這個詞出現的次數找出來
    if count == max_freq:
        most_common.append(word)
    if count == min_freq:
        least_common.append(word)

# Step 4: Result
print("詞頻統計：")
print(word_count)

print(f"出現最多次的詞：{most_common}，次數：{max_freq}")
print(f"出現最少次的詞：{least_common}，次數：{min_freq}")

"""## Question 2: Capital Quiz

p418 in textbook

Create a dictionary from colab_file

### 1. 匯入套件
"""

import pandas as pd
import random

"""### 2. 從 Wikipedia 抓表格"""

df_tables=pd.read_html("https://en.wikipedia.org/wiki/List_of_capitals_in_the_United_States")
print(f"這個網頁有{len(df_tables)}張表格")

df_tables

us_states=df_tables[2]  #拿第三個表格就好
us_states

"""### 3. 只取出「州名」和「首都」欄位"""

us_simple=us_states[[us_states.columns[0],us_states.columns[1]]]
us_simple
# 標題真的就兩格 超醜

"""### 4. 轉成 list"""

state_1=us_simple[us_simple.columns[0]].to_list() #將dataframe的第一個欄位的資料轉成list
capital_1=us_simple[us_simple.columns[1]].to_list() #將dataframe的第二個欄位的資料轉成list
del state_1[-1] #刪掉註解
del capital_1[-1] #刪掉註解
print(state_1)
print(capital_1)

"""### 5. 出題與判斷是否正確"""

r_int=random.randint(0,49)  #從 0 到 49 之間隨機抽一個整數，當作題目的 index，用同一個 r_int 來抓州名和正確答案，就不用用到dict了

input_str=f"the capital of {state_1[r_int]} is "
answer_str=input(input_str)

if answer_str.strip().lower() == capital_1[r_int].lower(): # 記得全部轉小寫，不然電腦會當Newyork和newyork不一樣
    print("Correct!")
else:
    print(f"Wrong. The correct answer is {capital_1[r_int]}")