# -*- coding: utf-8 -*-
"""111208094_hw1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTjc-nuHQ2LLnnDG9g0JdyiunNlHdA9c

# (1)	Textbook p201 (10) [15%]

Write a program that uses nested loops to draw this pattern:
* output:
~~~
##
# #
#  #
#   #
#    #
#     #
~~~
"""

# 作答區(1)
for i in range(6):
  print(f"#{' ' * i}#")

"""# (2)	Textbook p200 (4) [15%]

The distance a vehicle travels can be calculated as follows:
<center>distance = speed × time</center>

* For example, if a train travels 40 miles per hour for three hours, the distance traveled is 120 miles. Write a program that asks the user for the speed of a vehicle (in miles per hour) and the number of hours it has traveled. It should then use a loop to display the distance the vehicle has traveled for each hour of that time period. Here is an example of the desired output:
~~~
What is the speed of the vehicle in mph? 40
How many hours has it traveled? 3
Hour Distance_Traveled
1 40
2 80
3 120
~~~
"""

# 作答區(2)
import pandas as pd

speed = float(input("What is the speed of the vehicle in mph? "))
hours = int(input("How many hours has it traveled? "))

data = {"Hour": [], "Distance Traveled (miles)": []}

for i in range(1, hours + 1):
    data["Hour"].append(i)
    data["Distance Traveled (miles)"].append(i * speed)

df = pd.DataFrame(data)
print(df)

"""# (3)	Textbook p199 (4) [10%]

Write a loop that asks the user to enter a number. The loop should iterate 10 times and keep a running total of the numbers entered.
* For example:
~~~
Please enter a number: 1
Please enter a number: 2
Please enter a number: 3
Please enter a number: 1
Please enter a number: 3
Please enter a number: 4
Please enter a number: 2
Please enter a number: 1
Please enter a number: 4
Please enter a number: 1
The total of the above numbers: 22
~~~
"""

# 作答區(3)
total=0
for i in range(1,11):
  x=int(input("Please enter a number:"))
  total+=x
print("The total of the above numbers: ",total)

"""# (4)	Textbook p154 (9) [20%]

The Fast Freight Shipping Company charges the following rates:

<table border="1">
  <tr>
    <th>Weight of Package</th>
    <th>Rate per Pound</th>
  </tr>
  <tr>
    <td>2 pounds or less</td>
    <td>$ 1.10</td>
  </tr>
  <tr>
    <td>Over 2 pounds but not more than 6 pounds</td>
    <td>$ 2.20</td>
  </tr>
  <tr>
    <td>Over 6 pounds but not more than 10 pounds</td>
    <td>$ 3.70</td>
  </tr>
  <tr>
    <td>Over 10 pounds</td>
    <td>$ 3.80</td>
  </tr>
</table>

Write a program that asks the user to enter the weight of a package and then displays the shipping charges.
* For example (1):
~~~
Please enter the weight of a package: 10
The shipping charges: $ 37.000000
~~~

* For example (2):
~~~
Please enter the weight of a package: 1.5
The shipping charges: $ 1.650000
~~~
"""

# 作答區(4)
weight = float(input("Please enter the weight of a package: "))

if weight <= 2:
    charge = 1.10 * weight
elif weight <= 6:
    charge = 2.20 * weight
elif weight <= 10:
    charge = 3.70 * weight
else:
    charge = 3.80 * weight

print(f"The shipping charges: ${charge:.6f}")

# 作答區(4)
weight = float(input("Please enter the weight of a package: "))

if weight <= 2:
    charge = 1.10 * weight
elif weight <= 6:
    charge = 2.20 * weight
elif weight <= 10:
    charge = 3.70 * weight
else:
    charge = 3.80 * weight

print(f"The shipping charges: ${charge:.6f}")

"""# (5)	Textbook p153 (5) [20%]

The colors red, blue, and yellow are known as the primary colors because they cannot be made by mixing other colors. When you mix two primary colors, you get a secondary color, as shown here:
* When you mix red and blue, you get purple.
* When you mix red and yellow, you get orange.
* When you mix blue and yellow, you get green.

Design a program that prompts the user to enter the names of two primary colors to mix. If the user enters anything other than “red,” “blue,” or “yellow,” the program should display an error message. Otherwise, the program should display the name of the secondary color that results.

* For example (1):
~~~
Please enter the first color: red
Please enter the second color: red
The mixed color is red.
~~~

* For example (2):
~~~
Please enter the first color: red
Please enter the second color: blue
The mixed color is purple.
~~~

* For example (3):
~~~
Please enter the first color: purple
Please enter the second color: blue
The colors you entered are not correct.
~~~
"""

# 作答區(5)
print("輸入的要全部都是小寫字母，不要按到空白喔")
color1 = input("Please enter the first color: ")
color2 = input("Please enter the second color: ")

if color1 not in ["red", "blue", "yellow"] or color2 not in ["red", "blue", "yellow"]:
    print("The colors you entered are not correct.")
elif color1 == color2:
    print(f"The mixed color is {color1}.")
elif (color1 == "red" and color2 == "blue") or (color1 == "blue" and color2 == "red"):
    print("The mixed color is purple.")
elif (color1 == "red" and color2 == "yellow") or (color1 == "yellow" and color2 == "red"):
    print("The mixed color is orange.")
elif (color1 == "blue" and color2 == "yellow") or (color1 == "yellow" and color2 == "blue"):
    print("The mixed color is green.")

# By Chat GPT

color1 = input("Please enter the first color: ").strip().lower()
color2 = input("Please enter the second color: ").strip().lower()

primary_colors = {"red", "blue", "yellow"}

if color1 not in primary_colors or color2 not in primary_colors:
    print("The colors you entered are not correct.")
elif color1 == color2:
    print(f"The mixed color is {color1}.")
else:
    mix_colors = {
        frozenset(["red", "blue"]): "purple", #frozenset (不可變集合) 可用來儲存顏色組合
        frozenset(["red", "yellow"]): "orange",
        frozenset(["blue", "yellow"]): "green"
    }
    result = mix_colors.get(frozenset([color1, color2]))
    print(f"The mixed color is {result}.")

print("輸入的要全部都是小寫字母，不要按到空白喔")
color1 = input("Please enter the first color: ")
color2 = input("Please enter the second color: ")

if color1 not in ["red", "blue", "yellow"] or color2 not in ["red", "blue", "yellow"]:
    print("The colors you entered are not correct.")
elif color1 == color2:
    print(f"The mixed color is {color1}.")
elif (color1 == "red" and color2 == "blue") or (color1 == "blue" and color2 == "red"):
    print("The mixed color is purple.")
elif (color1 == "red" and color2 == "yellow") or (color1 == "yellow" and color2 == "red"):
    print("The mixed color is orange.")
elif (color1 == "blue" and color2 == "yellow") or (color1 == "yellow" and color2 == "blue"):
    print("The mixed color is green.")

"""# (6)	Textbook p200 (6) [20%]

Write a program that displays a table of the Celsius temperatures 0 through 20 and their Fahrenheit equivalents. The formula for converting a temperature from Celsius to Fahrenheit is
* F = 9/5 * C + 32
where F is the Fahrenheit temperature and C is the Celsius temperature. Your program must use a loop to display the table.
"""

# 作答區(6)
import pandas as pd

data = {"Celsius": [], " Fahrenheit": []}

for C in range(0, 21):
    F = 9/5 * C + 32
    data["Celsius"].append(C)
    data[" Fahrenheit"].append(F)

df = pd.DataFrame(data)
print(df)